#cloud-config

hostname: tae-one

write-files:
    - path: /etc/conf.d/nfs
      permissions: '0644'
      content: |
        OPTS_RPC_MOUNTD=""
coreos:
  update:
    reboot-strategy: off
  units:
    - name: docker.service
      command: start
      enable: true
    - name: docker-sabnzbd.service
      command: start
      content: |
        [Unit]
        After=docker.service

        [Service]
        TimeoutSec=0

        ExecStartPre=/usr/bin/docker kill sabnzbd
        ExecStartPre=/usr/bin/docker rm sabnzbd
        ExecStartPre=/usr/bin/docker pull timhaak/sabnzbd

        ExecStart=/usr/bin/docker run -h sabnzbd --name="sabnzbd" -v /etc/docker/sabnzbd:/config -v /mnt/vol_1/share:/data -p 8080:8080 -p 9090:9090 timhaak/sabnzbd

        ExecStop=/usr/bin/docker stop sabnzbd

        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target
    - name: docker-plex.service
      command: start
      content: |
        [Unit]
        After=docker.service

        [Service]
        TimeoutSec=0

        ExecStartPre=/usr/bin/docker kill plex
        ExecStartPre=/usr/bin/docker rm plex
        ExecStartPre=/usr/bin/docker pull timhaak/plex

        ExecStart=/usr/bin/docker run -h plex --name "plex" -v /etc/docker/plex:/config -v /mnt/vol_1/share:/data -p 32400:32400 timhaak/plex

        ExecStop=/usr/bin/docker stop plex

        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target
    - name: docker-sickbeard.service
      command: start
      content: |
        [Unit]
        After=docker.service

        [Service]
        TimeoutSec=0

        ExecStartPre=/usr/bin/docker kill sickbeard
        ExecStartPre=/usr/bin/docker rm sickbeard
        ExecStartPre=/usr/bin/docker pull timhaak/sickbeard

        ExecStart=/usr/bin/docker run -h sickbeard --name="sickbeard" -v /etc/docker/sickbeard:/config -v /mnt/vol_1/share:/data -p 8081:8081 timhaak/sickbeard

        ExecStop=/usr/bin/docker stop sickbeard

        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target
    - name: docker-couchpotato.service
      command: start
      content: |
        [Unit]
        After=docker.service

        [Service]
        TimeoutSec=0

        ExecStartPre=/usr/bin/docker kill couchpotato
        ExecStartPre=/usr/bin/docker rm couchpotato
        ExecStartPre=/usr/bin/docker pull timhaak/couchpotato

        ExecStart=/usr/bin/docker run -h couchpotato --name="couchpotato" -v /etc/docker/couchpotato:/config -v /etc/docker/couchpotato:/data -v /mnt/vol_1/share:/movies -p 5050:5050 timhaak/couchpotato

        ExecStop=/usr/bin/docker stop couchpotato

        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target
    - name: rpc-statd.service
      command: start
      enable: true
    - name: home.network
      runtime: true
      content: |
        [Match]
        Name=enp0s25

        [Network]
        Address=192.168.11.10/24
        Gateway=192.168.11.1
        DNS=8.8.8.8
        DNS=8.8.4.4
users:
  - name: core
    passwd: $6$rounds=4096$okocwVWBdlLA$G5WtoBOKCGirVnSIIpaGxBEhNsJktLMpy54GylKw8f202Mbv.k8Bw/z7x.5Ztb03pMg7E/lmnh3ZfEXtqvgQZ0
  - groups:
      - sudo
      - docker
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfdmWUV2Q1kEsd9Ow6BjmYT6Vi3tUFfF01h8Nmz14E5OUN8h7tYr0ppGySYyhzcjxpaXKexGg49TNgL8L2W4MDqCy0hD4sXsYwPzSdCpWVQkIjY/uSwTGXbKRG8wQUyMkKWpU72KtAE1G+dbqjlygJrhIsUxmDz6qB/2vFIPpfWkiyCkT/4UsQBeaqGcvw4tgq90ZdEucARd+3gJM/7Mr/gQTHhCNYlYcSsO81lIfvkYzr8cDcTJNfW3PsP8KmuAumAy+5ML+VTaskvdQn4NkHc5sDWYZ7zW5qaTHN4Sn1OZCfRYM/jbY1s/iIoiWqMpEffqyt7fuVxXZ2SNsxmMGd tae.one@gmail.com
  - name: tae
    passwd: $6$rounds=4096$okocwVWBdlLA$G5WtoBOKCGirVnSIIpaGxBEhNsJktLMpy54GylKw8f202Mbv.k8Bw/z7x.5Ztb03pMg7E/lmnh3ZfEXtqvgQZ0
  - groups:
      - sudo
      - docker
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfdmWUV2Q1kEsd9Ow6BjmYT6Vi3tUFfF01h8Nmz14E5OUN8h7tYr0ppGySYyhzcjxpaXKexGg49TNgL8L2W4MDqCy0hD4sXsYwPzSdCpWVQkIjY/uSwTGXbKRG8wQUyMkKWpU72KtAE1G+dbqjlygJrhIsUxmDz6qB/2vFIPpfWkiyCkT/4UsQBeaqGcvw4tgq90ZdEucARd+3gJM/7Mr/gQTHhCNYlYcSsO81lIfvkYzr8cDcTJNfW3PsP8KmuAumAy+5ML+VTaskvdQn4NkHc5sDWYZ7zW5qaTHN4Sn1OZCfRYM/jbY1s/iIoiWqMpEffqyt7fuVxXZ2SNsxmMGd tae.one@gmail.com
