#cloud-config

hostname: media-server

write-files:
    - path: /etc/conf.d/nfs
      permissions: '0644'
      content: |
        OPTS_RPC_MOUNTD=""
coreos:
  update:
    reboot-strategy: off
  etcd:
    addr: 192.168.11.10:4001
    peer-addr: 192.168.11.10:7001
  units:
    - name: rpc-statd.service
      command: start
      enable: true
    - name: mnt-nfs.mount
      command: start
      content: |
        [Mount]
        What=192.168.11.36:/mnt/array1/Sakai
        Where=/mnt/nfs
        type=nfs
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: home.network
      runtime: true
      content: |
        [Match]
        Name=enp0s25

        [Network]
        Address=192.168.11.10/24
        Gateway=192.168.11.1
        DNS=8.8.8.8
        DNS=8.8.4.4
users:
  - name: core
    passwd: $6$rounds=4096$okocwVWBdlLA$G5WtoBOKCGirVnSIIpaGxBEhNsJktLMpy54GylKw8f202Mbv.k8Bw/z7x.5Ztb03pMg7E/lmnh3ZfEXtqvgQZ0
  - groups:
      - sudo
      - docker
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfdmWUV2Q1kEsd9Ow6BjmYT6Vi3tUFfF01h8Nmz14E5OUN8h7tYr0ppGySYyhzcjxpaXKexGg49TNgL8L2W4MDqCy0hD4sXsYwPzSdCpWVQkIjY/uSwTGXbKRG8wQUyMkKWpU72KtAE1G+dbqjlygJrhIsUxmDz6qB/2vFIPpfWkiyCkT/4UsQBeaqGcvw4tgq90ZdEucARd+3gJM/7Mr/gQTHhCNYlYcSsO81lIfvkYzr8cDcTJNfW3PsP8KmuAumAy+5ML+VTaskvdQn4NkHc5sDWYZ7zW5qaTHN4Sn1OZCfRYM/jbY1s/iIoiWqMpEffqyt7fuVxXZ2SNsxmMGd tae.one@gmail.com
